### PR TITLE
add failure enum with argument test

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
@marc-mabe what do you think?

Maybe this test case is not really needed, but...

1) I want to get your opinion on that.
2) Maybe the test-case is still needed so this behaviour is not going to break with future releases.

**Comment by marc-mabe** [comment]
I'm not entirely sure.
Where this feature is possible right now already it breaks liskovsches substitutionsprinzip as you are adding a requirement argument. In case of an enumeration the methods are defined by constants without any arguments.

So basically the methods are known (not defined) by constant names known without expecting arguments but this is an implementation detail and a workaround as of missing enum support in PHP. On the other hand you are defining your own methods on the same level but in my opinion this overwrites already existing once defined by constant name where it breaks.

With buildin enums like this in PHP the problem would not exist as the method would not be needed and you would not overwrite somerhing.

**Comment by prolic** [comment]
Let's ignore possible Enum implementations in PHP core for now, as they do not exist.

A FailureEnum with additional message (or whatever) is a really nice I think.

It's also not really overridden, as __callStatic is not called at all. It is only an enum where you need additional values. However there is (currently) a problem with `::byValue`, `::byame` and so on, as you can still instantiate the FailureEnum without an additional parameter. Something I cannot change at the moment, because those methods are final.

**Comment by marc-mabe** [comment]
Sorry but still I don't thing that a good idea.

In my opinion if you define an enum like this:

```php
class ErrorCode extends Enum
{
    const INVALID_LENGTH = 1;
}
```

You have basically a class with a method defined defined as `public static function ErrorCode::INVALID_LENGTH()`. Internally it's done by `__callStatic()` but you shouldn't think to much about it as it's a **magic** method.

Also, you already noted, it's not safe as you still can get an enumerator instance by value, name and ordinal.

Why you don't define a simple failure class using an enum as key (based on above example) ?:

```php
class Failure
{
    /** @var ErrorCode */
    private $errorCode;
    /** @var string */
    private $message;
    public function __construct($errorCode, string $message)
    {
        $this->errorCode = ErrorCode::get($errorCode);
        $this->message = $message;
    }

    public function getErrorCode() : ErrorCode { return $this->errorCode; }
    public function getErrorMessage() : string { return $this->message; }

    public function __classStatic($errorName, array $args)
    {
        // TODO: validate $args
        return new self(ErrorCode::byName($errorName), $args[0]);
    }
}
```

**Comment by prolic** [comment]
Ok, I prefer your approach, thanks!

**Pull request closed without merging**
