### PR TITLE
Generics + better doc types PHPStan/psalm

### PR DESCRIPTION
**Pull request by marc-mabe**
* Introduces static code analyzes with PHPStan and psalm
* added generics using doc types for `EnumSet` and `EnumMap`
* Better doc types

### CODE REVIEW

**Comment by marc-mabe** [comment]
@prolic Hi - please could you take a look on this and share your opinions?

**Comment by prolic** [comment]
Sorry, super busy at the moment, but I try the next few days.

Sascha-Oliver Prolic


Am Sa., 11. Jan. 2020 um 09:45 Uhr schrieb Marc Bennewitz <
notifications@github.com>:

**Comment by marc-mabe** [comment]
All goodI'm super happy to get your help from time to timeAm 16.01.2020 02:07 schrieb Sascha-Oliver Prolic <notifications@github.com>:Sorry, super busy at the moment, but I try the next few days.



Sascha-Oliver Prolic





Am Sa., 11. Jan. 2020 um 09:45 Uhr schrieb Marc Bennewitz <

notifications@github.com>:

**Comment by marc-mabe** [comment]
Thanks for reviewing @prolic 👍 
I would like to get your opinion about IDE support as currently such Syntax is not natively supported by any of the IDEs I know. Means PHPStan gets better results but it reduces developer experience like autocompletion.

**Comment by prolic** [comment]
There is a plug-in for phpstorm, but when I tried I couldn't get the
expected results.

**Comment by prolic** [comment]
@marc-mabe What's the status here?

**Comment by marc-mabe** [comment]
The problem is this this breaks IDEs. I was hoping that at least some IDEs start to support it but it didn't until now.

As a workaround all the annotations needs to be prefixed.

Additionally I want to test this with psalm as well but didn't have time.

PS: my private time reduced drastically with the crises ... Would you like to be added as a collaborator?

**Comment by prolic** [comment]
@marc-mabe I maintain already at least 15 open source projects, one more doesn't make a difference at this point, lol. Sure, go ahead and add me.

**Comment by marc-mabe** [comment]
@prolic I have added you.

I have no idea where you get the time and energy to work on so many OS projects. You are my hero ;)

**Comment by marc-mabe** [comment]
Encountered a problem on how PHPStan interprets psalm type `list<non-empty-string>`.
Reported as bug here https://github.com/phpstan/phpstan/issues/3148

**Pull request merged**
